def test_intentional_failure():
    assert False, "This is an intentional failure to test CI."
